# Generated by Django 3.2.16 on 2024-12-13 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelancer_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutobidRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_countries', models.JSONField(default=list)),
                ('exclude_countries', models.JSONField(default=list)),
                ('payment_verified', models.BooleanField(default=False)),
                ('required_skills', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
