# Generated by Django 4.2.7 on 2024-12-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_tool', '0002_autobidrule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutobidRule',
        ),
    ]
