# Generated by Django 5.1.4 on 2024-12-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_tool', '0004_autobidrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobidrule',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='autobid_rules', to='freelancer_tool.bid'),
        ),
    ]
